### PR TITLE
extra check to avoid "notice" level error.

### PR DESCRIPTION
**Pull request by stjohn9**
To avoid a "Notice" level error, I've added a check to see if $remoteAuth is an email.

### CODE REVIEW

**Comment by PaulPoulain** [comment]
general comment : can you provide a way to reproduce the problem ?
additional comment: why not (also ?) use HTML5 validator : <input type="email" placeholder="Enter your email"> ?

**Comment by stjohn9** [comment]
It is absolutely non-critical, however in development environments I tend to set my php error reporting like so (in php.ini file): error_reporting = E_ALL
This displays "notice" level errors which include things like non-declared variables and such.
to reproduce this error, set error_reporting to "E_ALL", start a fresh browser session, and use a non-email account to signin to coral (I use auth via .htaccess).
It will produce:
Notice: Undefined offset: 1 in C:\Program Files (x86)\Apache24\htdocs\coral\usage\user.php on line 81
(since $remoteAuth doesn't contain an @ char.)

my php ver: 5.6.14 with apache2.4.17 on windows machine.

(btw, I was hoping to add a whole lot of these checks to avoid notice level warnings, however if its only in my interest, I can just keep it for myself.)

**Comment by PaulPoulain** [comment]
Thanks for the explanation.
I'm not a PHP-master-of-all-code. What are the general/usual guidelines for PHP code ? Is it considered as bad practise to have such notice-level errors ?
Is your way of fixing it the commonly adopted one ? (links welcomed)

(for now, I have not decided if it's also my interest or not ;-) )

**Comment by stjohn9** [comment]
Yes, it is bad practice having any kind of errors, including the notice level errors.
That said, it is also true, that with a well configured production server, these errors are [mostly] ignore-able, however, even then, it can produce a whole lot of logged errors, leading to performance issues.

General Philosophy regarding notice level errors:
http://www.sitepoint.com/why-suppressing-notices-is-wrong/

More about PHP Error Handling, and use of isset/empty:
http://kunststube.net/isset/

please take both sites with a pitch of salt, I mostly agree with them.

It is a much-discussed subject, if fact if you google anything about "php notice level errors" most results will link to "how to disable errors"... but yeah, I believe that it is best to fix instead of hiding.

**Comment by remocrevo** [comment]
@stjohn9 Thanks for your answers and the links. We would love to have these PHP Notices fixed. I think it would be best to provide a single pull request that contains as many of these fixes as possible, to minimize duplicated effort to test and merge.  But if you only have time to fix some, we will take whatever help you want to give. Thanks again!

**Comment by jeffnm** [comment]
I agree. I'd like to see all of our notice level errors fixed.

**Comment by stjohn9** [comment]
@remocrevo I would gladly fix the PHP Notices (and other bumps) however I'm new to Github. Not sure how to make a single pull request for changes on multiple files. any tips?

**Comment by remocrevo** [comment]
GitHub has great documentation about creating a pull request: https://help.github.com/articles/using-pull-requests/

The key seems to be the branch you are working in. When you first edit code on GitHub, it creates a forked repository for you and a new branch which contains the change you just committed.  At that point, you should be able to choose that branch in the branch dropdown, navigate to other files, edit those files (possibly requiring separate commits, I'm not sure) and eventually submit them all as a single pull request.  Give it a try and post any questions here or on the CORAL Discussion List <CORAL-ERM@listserv.nd.edu>.

**Comment by remocrevo** [comment]
@stjohn9 I just realized that pull request #30 might already address most of your concerns.  So I suggest you look at that before doing additional work on this.  Sorry I didn't notice this sooner.

**Comment by jeffnm** [comment]
@remocrevo @stjohn9 Actually, I think #30 is only changing the SushiService.php file, so I'm sure there are other Notice level warnings that still need to be fixed.

**Comment by stjohn9** [comment]
@remocrevo Hi, actually I haven't gotten to the SushiService.php file yet. I hope I'm not going about it in the wrong way, but to have a single pull request with multiple files, I more or less started over: github created a fork: https://github.com/stjohn9/usage which contains a branch: https://github.com/stjohn9/usage/tree/stjohn9-NoticeFix which contains all the files I've been working on up until now.

Have I just made a mess of things, or should I carry on as I am doing?
Thanks for your patience.

**Comment by PaulPoulain** [comment]
You're not doing it the wrong way. But you may face an annoying side effect: need to rebase frequently.
A better option, imo, would be to have smaller groups of patches, each in a git branch. You push them on your "fork", then you do a merge request for each of them.

**Comment by jeffnm** [comment]
I see you included this fix in #32, which is great, but I'm going to close this pull request so that it doesn't get merged cause a conflict with #32. I'll start reviewing #32 and see if we can get it merged in soon. Thanks for all your work on this!

**Pull request closed without merging**
